# Site settings
title: AP Haitille
email: huppuguru@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/apua-haitille-jami/" # the subpath of your site, e.g. /blog/
url: "http://jamiprinssi.github.io # the base hostname & protocol for your site

twitter_username: jamiprinssi
github_username: jamiprinssi

# Build settings
markdown: kramdown
highlighter: rouge
encoding: utf-8